// Parallel git worktrees — one workspace per agent or per job, so several
// agents can work ONE repository at the same time without standing on each
// other (his item 7).
//
// WHY A WORKTREE AND NOT A CLONE. A clone copies the whole history per agent
// and its branches are invisible to the others. `git worktree` gives each agent
// its own folder and its own checked-out branch against the SAME object store,
// so five agents cost five working trees and one history — and every branch
// they make is already in the repository the pull request will be opened from.
//
// ESTABLISHED BY RUNNING git 2.52.0.windows.1 ON THIS MACHINE, not remembered:
//  • `git worktree add [-b <branch>] <path> [<commit-ish>]` — one worktree, one
//    branch. Verified.
//  • A branch may be checked out in ONE worktree only. Asking twice fails with
//    "fatal: a branch named 'x' already exists". Verified — this is the collision
//    guard the whole design leans on, and it is git's, not ours.
//  • `git worktree list --porcelain` reports every worktree with its branch.
//  • `git worktree remove <path>` REFUSES a worktree with modified or untracked
//    files ("use --force to delete it"). Verified. So cleanup never silently
//    eats work: it reports the mess and leaves it alone unless told twice.
//  • Removing a worktree does NOT delete its branch. Verified. That is the
//    behaviour we want — the branch is what the pull request points at.
//  • `git worktree prune` clears the admin entry for a folder deleted by hand.
//
// THE QUOTING LAW (run.ts) IS NOT RELAXED HERE. Every argument still goes
// through the allowlist, so no message, title or file name written by an agent
// or a person may reach a command line:
//  • branch names are GENERATED by `branchNameFor`, never accepted as text;
//  • commit messages go in on STDIN — `git commit -F -` was verified on this
//    machine with a message containing quotes, `$` and `&`;
//  • every other call runs with `cwd` set to the worktree instead of putting a
//    path in argv at all.
//
// NOTHING IN THIS FILE TOUCHES A REMOTE. Fetching, pushing and pull requests
// live in `github.ts`, behind the approval gate, precisely so that "work in a
// worktree" and "let something leave this machine" can never be the same
// decision.
import fs from "node:fs";
import path from "node:path";
import { run, Runner } from "./run.js";

/** A worktree the engine prepared for one agent (and usually one job). */
export interface Worktree {
  /** the repository this was carved out of — the folder holding `.git` */
  repoDir: string;
  /** the agent's own checkout. Never inside `repoDir`. */
  path: string;
  /** the branch checked out in it — always ours, always generated */
  branch: string;
  /** what it was branched FROM, so a pull request knows where to aim */
  base: string;
  agentId: string;
  taskId?: string;
}

export interface GitWorkspaceOptions {
  /** tests inject a fake */
  runner?: Runner;
  /** the folder worktrees are created under — the engine's own data folder */
  root: string;
  /** leash on any one git command */
  timeoutMs?: number;
  log?: (message: string) => void;
}

/** What `git status --porcelain` said, in words rather than punctuation. */
export interface WorkingTreeState {
  clean: boolean;
  /** paths git reported as changed, added or untracked */
  files: string[];
}

export interface CommitResult {
  /** false when there was nothing to commit — that is a fact, not a failure */
  committed: boolean;
  /** the new commit's full id, read back from git */
  sha?: string;
  /** how many paths went into it */
  files: number;
}

/** A git command came back non-zero and the caller cannot carry on. */
export class GitError extends Error {
  constructor(public readonly command: string, public readonly detail: string) {
    super(`git ${command} failed: ${detail}`);
    this.name = "GitError";
  }
}

// --------------------------------------------------------------- branch names

/**
 * Every Cloud9 branch starts with this, so his repository always says at a
 * glance which branches an agent made and which he made himself.
 */
export const BRANCH_PREFIX = "cloud9";

/**
 * THE ONE PLACE A BRANCH NAME IS MADE.
 *
 * It is generated from ids we already hold, never from anything typed. That is
 * what lets `run.ts` keep refusing to escape: the name is clean by construction
 * rather than clean by careful quoting. `isSafeBranchName` below is the second
 * pair of eyes, and every caller passes through it.
 */
export function branchNameFor(
  input: { agentId: string; taskId?: string; at?: number },
): string {
  const who = slug(input.agentId) || "agent";
  const what = input.taskId ? slug(input.taskId) : "";
  const when = (input.at ?? Date.now()).toString(36);
  const tail = what ? `${what}-${when}` : when;
  return `${BRANCH_PREFIX}/${who}-${tail}`;
}

/** Lower-case, letters/digits/dashes only, never leading or trailing dashes. */
function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}

/**
 * Is this a branch name git will accept AND our command line will carry?
 *
 * The two questions are asked together on purpose. A name that git likes but
 * the allowlist refuses would fail confusingly at spawn time; a name the
 * allowlist likes but git refuses would fail confusingly at checkout. Both
 * answers live here.
 */
export function isSafeBranchName(name: string): boolean {
  if (!name.startsWith(`${BRANCH_PREFIX}/`)) return false;
  if (name.length > 120) return false;
  // git's own ref rules, the parts that matter for a name we generate
  if (name.includes("..") || name.includes("//")) return false;
  if (name.endsWith("/") || name.endsWith(".") || name.endsWith(".lock")) return false;
  if (name.startsWith("-")) return false;
  // and the run.ts allowlist, minus the characters git would reject anyway
  return /^[a-z0-9/._-]+$/.test(name);
}

/** The folder one worktree lives in. Under the engine's data folder, never the repo. */
export function worktreePathFor(root: string, branch: string): string {
  return path.join(root, "worktrees", branch.replace(/\//g, "-"));
}

// ------------------------------------------------------------- the workspace

/**
 * The local half of "an agent works like a developer": make it a workspace,
 * let it work, commit what it did, tidy up.
 *
 * Every method here is safe to run without asking anybody, because none of them
 * can be seen from outside this computer.
 */
export class GitWorkspace {
  private runner: Runner;
  private timeoutMs: number;
  private log: (message: string) => void;

  constructor(private opts: GitWorkspaceOptions) {
    this.runner = opts.runner ?? run;
    this.timeoutMs = opts.timeoutMs ?? 60_000;
    this.log = opts.log ?? ((m: string) => console.log(`[git] ${m}`));
  }

  /** Run one git command in a folder. The folder goes in `cwd`, never in argv. */
  async git(cwd: string, args: string[]): Promise<{ code: number | null; out: string; err: string }> {
    const result = await this.runner("git", args, { cwd, timeoutMs: this.timeoutMs });
    if (result.notFound) throw new GitError(args[0] ?? "", "git is not installed on this computer");
    return { code: result.code, out: result.stdout, err: result.stderr };
  }

  /** Is this folder a git repository we can work in? */
  async isRepo(repoDir: string): Promise<boolean> {
    try {
      const r = await this.git(repoDir, ["rev-parse", "--is-inside-work-tree"]);
      return r.code === 0 && r.out.trim() === "true";
    } catch {
      return false;
    }
  }

  /**
   * The branch a pull request should aim at.
   *
   * Read from the repository, never assumed: this project's own default branch
   * is `master`, and half the world's is `main`, so guessing either one would
   * be wrong for the other half. `refs/remotes/origin/HEAD` is the remote's own
   * answer (verified on this repository: it reads `refs/remotes/origin/master`).
   * If there is no remote yet, the branch we are standing on is the honest
   * fallback.
   */
  async defaultBranch(repoDir: string): Promise<string> {
    const remote = await this.git(repoDir, ["symbolic-ref", "--quiet", "refs/remotes/origin/HEAD"]);
    const ref = remote.out.trim();
    if (remote.code === 0 && ref.startsWith("refs/remotes/origin/")) {
      return ref.slice("refs/remotes/origin/".length);
    }
    const head = await this.git(repoDir, ["rev-parse", "--abbrev-ref", "HEAD"]);
    const name = head.out.trim();
    if (head.code === 0 && name && name !== "HEAD") return name;
    throw new GitError("rev-parse", "this repository has no branch to work from yet");
  }

  /**
   * Give one agent its own checkout of one repository.
   *
   * The branch is created here and only here, so two agents preparing at the
   * same moment get two different names. If they somehow did not, git itself
   * refuses the second one — verified — and that refusal is reported rather
   * than worked around.
   */
  async prepare(input: {
    repoDir: string;
    agentId: string;
    taskId?: string;
    /** what to branch from — defaults to the repository's own default branch */
    base?: string;
    at?: number;
  }): Promise<Worktree> {
    if (!await this.isRepo(input.repoDir)) {
      throw new GitError("rev-parse", "that folder is not a git repository");
    }
    const base = input.base ?? await this.defaultBranch(input.repoDir);
    const branch = branchNameFor(input);
    if (!isSafeBranchName(branch)) {
      throw new GitError("worktree add", `refusing an unusable branch name: ${branch}`);
    }
    const target = worktreePathFor(this.opts.root, branch);
    if (fs.existsSync(target)) {
      throw new GitError("worktree add", "a workspace with that name is already here");
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });

    const added = await this.git(input.repoDir, ["worktree", "add", "-b", branch, target, base]);
    if (added.code !== 0) {
      throw new GitError("worktree add", firstLine(added.err || added.out));
    }
    this.log(`prepared ${branch} for agent ${input.agentId}`);
    return {
      repoDir: input.repoDir, path: target, branch, base,
      agentId: input.agentId, ...(input.taskId ? { taskId: input.taskId } : {}),
    };
  }

  /** What has the agent actually changed in there? */
  async status(wt: Worktree): Promise<WorkingTreeState> {
    const r = await this.git(wt.path, ["status", "--porcelain"]);
    if (r.code !== 0) throw new GitError("status", firstLine(r.err || r.out));
    const files = r.out.split(/\r?\n/)
      .map(line => line.slice(3).trim())
      .filter(Boolean);
    return { clean: files.length === 0, files };
  }

  /**
   * Commit everything the agent changed, with a message it wrote.
   *
   * The message never reaches a command line: `git commit -F -` takes it on
   * standard input, verified on this machine with a message containing quotes,
   * `$` and `&`. The first line becomes the subject, and `gh pr create --fill`
   * later lifts the pull request's title straight out of it — which is how a
   * title written by an agent gets onto GitHub without ever being an argument.
   *
   * Nothing to commit is reported as `committed: false`, not as an error: "the
   * agent changed nothing" is a true and useful answer.
   */
  async commitAll(wt: Worktree, message: { title: string; body?: string }): Promise<CommitResult> {
    const state = await this.status(wt);
    if (state.clean) return { committed: false, files: 0 };

    const added = await this.git(wt.path, ["add", "-A"]);
    if (added.code !== 0) throw new GitError("add", firstLine(added.err || added.out));

    const text = commitMessage(message);
    const result = await this.runner("git", ["commit", "-F", "-"], {
      cwd: wt.path, timeoutMs: this.timeoutMs, stdin: text,
    });
    if (result.code !== 0) {
      throw new GitError("commit", firstLine(result.stderr || result.stdout));
    }
    const sha = await this.git(wt.path, ["rev-parse", "HEAD"]);
    return {
      committed: true,
      ...(sha.code === 0 && sha.out.trim() ? { sha: sha.out.trim() } : {}),
      files: state.files.length,
    };
  }

  /** Has this worktree got commits the base branch has not? */
  async hasNewCommits(wt: Worktree): Promise<boolean> {
    const r = await this.git(wt.path, ["rev-list", "--count", `${wt.base}..HEAD`]);
    if (r.code !== 0) return false;
    return Number(r.out.trim()) > 0;
  }

  /** Every worktree this repository currently has, branch included. */
  async list(repoDir: string): Promise<{ path: string; branch?: string }[]> {
    const r = await this.git(repoDir, ["worktree", "list", "--porcelain"]);
    if (r.code !== 0) throw new GitError("worktree list", firstLine(r.err || r.out));
    const out: { path: string; branch?: string }[] = [];
    for (const block of r.out.split(/\r?\n\r?\n/)) {
      const dir = /^worktree (.+)$/m.exec(block)?.[1]?.trim();
      if (!dir) continue;
      const ref = /^branch (.+)$/m.exec(block)?.[1]?.trim();
      out.push({ path: dir, ...(ref ? { branch: ref.replace(/^refs\/heads\//, "") } : {}) });
    }
    return out;
  }

  /**
   * Put the workspace away.
   *
   * THE BRANCH SURVIVES ON PURPOSE — verified: `git worktree remove` leaves it
   * alone, and it is what the pull request points at. Deleting it here would
   * quietly throw away the very thing the round produced.
   *
   * Uncommitted work is not thrown away either. git refuses to remove a dirty
   * worktree (verified), and that refusal is passed straight through unless the
   * caller explicitly says `force` — which is a second, deliberate decision.
   */
  async cleanup(wt: Worktree, opts: { force?: boolean } = {}): Promise<{ removed: boolean; reason?: string }> {
    const args = opts.force
      ? ["worktree", "remove", "--force", wt.path]
      : ["worktree", "remove", wt.path];
    const r = await this.git(wt.repoDir, args);
    if (r.code !== 0) {
      const reason = firstLine(r.err || r.out);
      this.log(`left ${wt.branch} in place: ${reason}`);
      return { removed: false, reason };
    }
    // a folder deleted by hand leaves an admin entry behind; this clears it
    await this.git(wt.repoDir, ["worktree", "prune"]);
    this.log(`cleaned up ${wt.branch}`);
    return { removed: true };
  }
}

/**
 * The one shape of a commit message: a subject line, a blank line, the rest.
 *
 * It matters more than it looks: `gh pr create --fill` reads the pull request's
 * title from the subject and its body from what follows, so this function is
 * also deciding what he will read on GitHub.
 */
export function commitMessage(message: { title: string; body?: string }): string {
  const title = message.title.replace(/\s+/g, " ").trim().slice(0, 72) || "Cloud9 agent changes";
  const body = (message.body ?? "").trim();
  return body ? `${title}\n\n${body}\n` : `${title}\n`;
}

function firstLine(text: string): string {
  return (text.split(/\r?\n/).find(l => l.trim()) ?? "").trim().slice(0, 200) || "no detail given";
}
